#!/usr/bin/python3

# We are not using string.count(substring) , as count() will not take into account the case of overlapping substrings.
# For example: "aaaaaaaaa".count("aaa") returns 3 which is wrong in our case

def _PatternCount(Text, Pattern): 
		count = 0
		textSize = len(Text)
		patternSize = len(Pattern)
		for i in range(0, textSize - patternSize +1):
			if Text[i:i+patternSize] == Pattern:
				count+=1
		return count

text="GATGGTAGACCGCTAACATATAGGCGCTAACGATGGCGCTAACACGCTAACCCCAAGGAAGCACGCTAACGCGCTAACACATCGCTAACGCGCTAACCGCTAACCGCTAACCGCTAACCGCTAACTTCGCTAACCACCGCTAACAACGCTAACGCGCTAACCGCTAACTGCGCTAACGGTGCCCGCGCTAACTTCCAGGGAAATGGTGCGCTAACGCCGCTAACTCGAACGCTAACCGCTAACGTTCGCTAACTCGCTAACCAGCGCTAACACGCTAACGCACAACGCTAACCGCTAACCGCTAACCGCTAACCGCTAACCGCTAACAGCCGCTAACGCCGCTAACACGCTAACGGTGTTTGGTGCGCTAACACAGCCACGCTAACTACCCGCTAACATCGGCGCTAACATCGCTAACACCGCTAACAGCGCTAACCGCTAACCGCTAACAGCGCTAACCCGCTAACAGTCGCTAACAGCGCTAACCACAGCGCTAACCGCTAACGTCATCGCTAACCGCCGCTAACTCGCTAACCGCTAACCGCTAACCGCTAACCCCGCTAACCGCTAACCGCGCTAACCCGGTGGCGCTAACCGCTAACCCGCTAACTCTTTCGCTAACCAACGCTAACCGCTAACCCGCTAACATCTTAGTCAGCGCGCTAACCCGCTAACCGCTAACACTCGCTAACCGCTAACCGCTAACAGCGCGCTAACCCGCTAACTTCGCTAACATTCCCGCTAACCTTTCCGCTAACGACCGCTAACACGCGCTAACCGCTAACCCACGCTAACAAATACGCTAACCACCCCCGCTAACTTATGTGATGCACGTCCGCTAACCGCTAACCCTATCGCTAACGTTTGGGCCTCCTCCGCTAACGCGCTAACACTCGCTAACCGCTAACCGCTAACTCTATCGCTAACTCCCGCTAACCCGCTAACCGCTAACGGCGCTAACCGCTAACCGCTAAC" 
a = _PatternCount(text,"CGCTAACC")
print("Pattern: CGCTAACC found ",a ,"times")

# Example run:
#$ ./PatternCount.py
# Pattern: CGCTAACC found  49 times
#
